version: "3.9" 

services:
  api:
    container_name: api
    restart: always
    build: api
    volumes:
      - ./api:/api
    ports:
      - 8000:8000
    
  # nginx:
  #   container_name: nginx
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx/nginx-conf.conf:/etc/nginx/conf.d/default.conf:ro
