FROM python:3.8-slim-buster

RUN mkdir /api

COPY requirements.txt /api

WORKDIR /api

RUN pip3 install -r requirements.txt

EXPOSE 8000

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
